### ISSUE TITLE
[BUG] - Could Not Establish Connection Error

### ISSUE THREAD

**Issue by MaisieCraft** [ZeroPointNothing/Ads-Be-Gone#16]
it gives an error saying (Could not establish connection. Receiving end does not exist.)
when you try to use it

**Comment by ZeroPointNothing** [comment]
Could you give more info? The template should have listed fields you were supposed to fill out.

**Comment by ZeroPointNothing** [comment]
For example, what websites does it happen on?

**Comment by ZeroPointNothing** [comment]
Hm. Odd. Can you open the console and send me a screenshot of it? (Press f12 while on Picrew and click the Console tab.)

**Comment by MaisieCraft** [comment]
i downloaded the newer version and its fixed now

**Comment by ZeroPointNothing** [comment]
I'm glad to hear it! Happy Browsing!
